/**
 * Códigos de error centralizados - sincronizados con el backend
 * Estos códigos deben coincidir exactamente con los del backend
 */
export const ErrorCodes = {
  // Errores de Cliente
  CLIENT_NOT_FOUND: "CLIENT_NOT_FOUND",
  CLIENT_ID_MISMATCH: "CLIENT_ID_MISMATCH",

  // Errores de Producto
  PRODUCT_NOT_FOUND: "PRODUCT_NOT_FOUND",
  PRODUCT_ID_MISMATCH: "PRODUCT_ID_MISMATCH",
  PRODUCT_INVALID_QUANTITY: "PRODUCT_INVALID_QUANTITY",
  PRODUCT_MISSING_WORKPACKAGE: "PRODUCT_MISSING_WORKPACKAGE",
  PRODUCT_DUPLICATE: "PRODUCT_DUPLICATE",

  // Errores de Venta
  SALE_NOT_FOUND: "SALE_NOT_FOUND",
  SALE_DETAIL_NOT_FOUND: "SALE_DETAIL_NOT_FOUND",
  SALE_CLIENT_NOT_FOUND: "SALE_CLIENT_NOT_FOUND",
  SALE_OBSERVATIONS_TOO_LONG: "SALE_OBSERVATIONS_TOO_LONG",
  SALE_DUPLICATE_PRODUCTS: "SALE_DUPLICATE_PRODUCTS",
  SALE_PRODUCT_INVALID_QUANTITY: "SALE_PRODUCT_INVALID_QUANTITY",
  SALE_PRODUCT_NOT_FOUND: "SALE_PRODUCT_NOT_FOUND",
  SALE_PRODUCT_MISSING_WORKPACKAGE: "SALE_PRODUCT_MISSING_WORKPACKAGE",

  // Errores de Filamento
  FILAMENT_NOT_FOUND: "FILAMENT_NOT_FOUND",
  FILAMENT_ID_MISMATCH: "FILAMENT_ID_MISMATCH",

  // Errores de Impresora
  PRINTER_NOT_FOUND: "PRINTER_NOT_FOUND",
  PRINTER_NOT_SELECTED: "PRINTER_NOT_SELECTED",

  // Errores de WorkPackage
  WORKPACKAGE_NOT_FOUND: "WORKPACKAGE_NOT_FOUND",
  WORKPACKAGE_ID_MISMATCH: "WORKPACKAGE_ID_MISMATCH",

  // Errores de Gasto
  EXPENSE_NOT_FOUND: "EXPENSE_NOT_FOUND",

  // Errores de Configuración del Sistema
  SYSTEM_CONFIG_NOT_FOUND: "SYSTEM_CONFIG_NOT_FOUND",
  SYSTEM_CONFIG_ID_MISMATCH: "SYSTEM_CONFIG_ID_MISMATCH",

  // Errores de Historial de Impresión
  PRINTING_HISTORY_NOT_FOUND: "PRINTING_HISTORY_NOT_FOUND",
  PRINTING_HISTORY_FILAMENT_NOT_FOUND: "PRINTING_HISTORY_FILAMENT_NOT_FOUND",

  // Errores de Suscripción
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
  SUBSCRIPTION_ALREADY_EXISTS: "SUBSCRIPTION_ALREADY_EXISTS",

  // Errores de Autenticación
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_USER_NOT_FOUND: "AUTH_USER_NOT_FOUND",
  AUTH_USER_LOCKED_OUT: "AUTH_USER_LOCKED_OUT",
  AUTH_USER_NOT_ALLOWED: "AUTH_USER_NOT_ALLOWED",
  AUTH_REQUIRES_TWO_FACTOR: "AUTH_REQUIRES_TWO_FACTOR",
  AUTH_REGISTRATION_FAILED: "AUTH_REGISTRATION_FAILED",
  AUTH_ROLE_ASSIGNMENT_FAILED: "AUTH_ROLE_ASSIGNMENT_FAILED",
  AUTH_PASSWORD_CHANGE_FAILED: "AUTH_PASSWORD_CHANGE_FAILED",
  AUTH_USER_ALREADY_EXISTS: "AUTH_USER_ALREADY_EXISTS",
  AUTH_USER_WITHOUT_TENANT: "AUTH_USER_WITHOUT_TENANT",

  // Errores de Validación General
  VALIDATION_ID_MISMATCH: "VALIDATION_ID_MISMATCH",
  VALIDATION_REQUIRED_FIELD: "VALIDATION_REQUIRED_FIELD",
  VALIDATION_INVALID_FORMAT: "VALIDATION_INVALID_FORMAT",

  // Errores del Sistema
  SYSTEM_INTERNAL_ERROR: "SYSTEM_INTERNAL_ERROR",
  SYSTEM_BAD_REQUEST: "SYSTEM_BAD_REQUEST",
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];

